### ISSUE TITLE
Can't run test

### ISSUE THREAD

**Issue by xReniar** [KatharaFramework/kathara-lab-checker#9]
When using this command:
`python3 -m kathara-lab-checker --config examples/configuration_palabra.json --no-cache`
I get:
/home/rainer/anaconda3/envs/kathara/bin/python3: No module named kathara-lab-checker

But when removing `python3 -m`:
`kathara-lab-checker --config configurationMirada.json --lab ../mirada/ --no-cache`
it works

**Comment by tcaiazzi** [comment]
Dear @xReniar, 

Can you provide a step-by-step guide to reproduce the error? 

Thanks for the help!
